image: Visual Studio 2017

install:
  - ps: Install-Product node 8 x86
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion

build_script:
  - nuget restore -Verbosity quiet
  - cd EmbeddedTerminal
  - npm install
  - cd ..
  - msbuild .\EmbeddedTerminal\EmbeddedTerminal.csproj /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

artifacts:
  - path: '**\*.vsix'
    name: WhackWhackTerminal